pluginManagement {
    repositories {
        maven {
            name = 'githubPackages'
            url = uri('https://maven.pkg.github.com/yuki-js/cinpo')
            credentials {
                username = providers.gradleProperty('gpr.user')
                        .orElse(providers.environmentVariable('GITHUB_ACTOR'))
                        .orNull
                password = providers.gradleProperty('gpr.key')
                        .orElse(providers.environmentVariable('GITHUB_TOKEN'))
                        .orNull
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'cinpo-template'
