pluginManagement {
    repositories {
        def githubPackagesUser = providers.gradleProperty('gpr.user')
                .orElse(providers.environmentVariable('GITHUB_ACTOR'))
        def githubPackagesKey = providers.gradleProperty('gpr.key')
                .orElse(providers.environmentVariable('GITHUB_TOKEN'))

        if (githubPackagesUser.isPresent() && githubPackagesKey.isPresent()) {
            maven {
                name = 'githubPackages'
                url = uri('https://maven.pkg.github.com/AokiApp/cinpo')
                credentials {
                    username = githubPackagesUser.get()
                    password = githubPackagesKey.get()
                }
            }
        }
        maven {
            name = 'githubPages'
            url = uri('https://AokiApp.github.io/cinpo')
        }
        maven {
            name = 'javacardPro'
            url = uri('https://mvn.javacard.pro/maven/')
        }
        maven {
            name = 'javacardProSnapshots'
            url = uri('https://mvn.javacard.pro/maven/SNAPSHOTS/')
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'cinpo-template'
