package app.aoki.cinpo.cli;

/**
 * Single source of truth for the CINPO version string.
 * <p>
 * This file is generated by the {@code generateVersionSource} Gradle task and
 * must not be edited manually. The version value is read from
 * {@code project.version} in {@code build.gradle}.
 */
public final class CinpoVersion {

    /** CINPO version, sourced from {@code project.version} in Gradle. */
    // BEGIN GENERATED — do not edit
    public static final String VERSION = "0.1.1";
    // END GENERATED

    private CinpoVersion() {
        throw new UnsupportedOperationException("utility class");
    }
}
